apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift-knative/eventing?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "release-v1.15" 
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: serverless-operator-135
    appstudio.openshift.io/component: kn-eventing-test-print-115
    pipelines.appstudio.openshift.io/type: build
  name: kn-eventing-test-print-115-on-push
  namespace: ocp-serverless-tenant
spec:
  params:
    - name: dockerfile
      value: openshift/ci-operator/knative-test-images/print/Dockerfile
    - name: build-args
      value: [ VERSION=release-1.35, ]
    - name: git-url
      value: '{{source_url}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/ocp-serverless-tenant/serverless-operator-135/kn-eventing-test-print:{{revision}}
    - name: revision
      value: '{{revision}}'
    - name: additional-tags
      value: [ release-1.35,  latest, ]
  pipelineRef:
    name: docker-build
  taskRunTemplate: {}
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        status: {}
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
